In [ ]:
import tensorflow as tf

In [9]:
traning_set=tf.keras.utils.image_dataset_from_directory(
    'train/train/',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),              
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,

)

Found 70295 files belonging to 38 classes.


In [10]:
validation_set=tf.keras.utils.image_dataset_from_directory(
    'valid/valid/',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),              #128
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,

)

Found 17572 files belonging to 38 classes.


In [4]:
for x,y in traning_set:
  print(x,x.shape)
  print(y,y.shape)
  break

tf.Tensor(
[[[[ 72.    69.75  88.5 ]
   [ 73.    71.    89.5 ]
   [ 74.25  72.75  90.75]
   ...
   [ 41.25  32.5   33.75]
   [ 44.75  29.25  35.25]
   [ 43.75  24.75  33.5 ]]

  [[159.   155.25 178.25]
   [151.   147.25 170.25]
   [152.75 149.   172.  ]
   ...
   [ 84.    73.5   79.25]
   [ 86.75  69.25  82.25]
   [ 79.5   57.    74.75]]

  [[155.5  151.25 178.5 ]
   [147.75 143.5  170.75]
   [155.   150.75 178.  ]
   ...
   [ 82.25  73.5   81.5 ]
   [ 97.25  80.    99.75]
   [ 95.75  72.75  99.25]]

  ...

  [[109.25 105.25 132.25]
   [113.   109.   136.  ]
   [124.5  120.5  147.5 ]
   ...
   [ 70.25  65.25  95.25]
   [ 70.5   65.5   95.5 ]
   [ 78.75  73.75 103.75]]

  [[118.25 114.25 141.25]
   [120.5  116.5  143.5 ]
   [114.75 110.75 137.75]
   ...
   [ 76.75  71.75 101.75]
   [ 73.    68.    98.  ]
   [ 73.75  68.75  98.75]]

  [[127.5  123.5  150.5 ]
   [105.5  101.5  128.5 ]
   [115.25 111.25 138.25]
   ...
   [ 70.75  65.75  95.75]
   [ 74.    69.    99.  ]
   [ 75.5   70.5  10

In [4]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout
from tensorflow.keras.models import Sequential

In [5]:
model=Sequential()

In [6]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [8]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [9]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [10]:
model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=512,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=1,strides=1))

In [11]:
model.add(Dropout(0.25))

In [12]:
model.add(Flatten())

In [13]:
model.add(Dense(units=1500,activation='relu'))

In [14]:
model.add(Dropout(0.4))

In [15]:
model.add(Dense(units=38,activation='softmax'))

In [ ]:
    model.compile(optimizer=tf.keras.optimizers.Adam(
        learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 126, 126, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 63, 63, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 63, 63, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 31, 31, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 31, 31, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 29, 29, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 14, 14, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 12, 12, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 6, 6, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 6, 6, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_9 (Conv2D)               │ (None, 4, 4, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 4, 4, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 4, 4, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 8192)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1500)           │    12,289,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 1500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 38)             │        57,038 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,058,762 (65.07 MB)

 Trainable params: 17,058,762 (65.07 MB)

 Non-trainable params: 0 (0.00 B)

In [18]:
training_history=model.fit(x=traning_set,validation_data=validation_set,epochs=10)

Epoch 1/10


2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2354s 1s/step - accuracy: 0.4514 - loss: 1.9402 - val_accuracy: 0.8286 - val_loss: 0.5289
Epoch 2/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2290s 1s/step - accuracy: 0.8499 - loss: 0.4755 - val_accuracy: 0.8997 - val_loss: 0.3082
Epoch 3/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2268s 1s/step - accuracy: 0.9110 - loss: 0.2710 - val_accuracy: 0.9209 - val_loss: 0.2453
Epoch 4/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2236s 1s/step - accuracy: 0.9414 - loss: 0.1809 - val_accuracy: 0.9398 - val_loss: 0.1835
Epoch 5/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2229s 1s/step - accuracy: 0.9549 - loss: 0.1353 - val_accuracy: 0.9485 - val_loss: 0.1576
Epoch 6/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2216s 1s/step - accuracy: 0.9679 - loss: 0.1011 - val_accuracy: 0.9485 - val_loss: 0.1716
Epoch 7/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2407s 1s/step - accuracy: 0.9713 - loss: 0.0872 - val_accuracy: 0.9536 - val_loss: 0.1447
Epoch 8/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2209s 1s/step - accuracy: 0.9770 - loss: 0.07

In [7]:
loaded_history_json

{'accuracy': [0.6375417709350586,
  0.8687958121299744,
  0.9214595556259155,
  0.9468098878860474,
  0.959072470664978,
  0.9696991443634033,
  0.973781943321228,
  0.9785475730895996,
  0.9792872667312622,
  0.9836688041687012],
 'loss': [1.2260605096817017,
  0.41059601306915283,
  0.24095740914344788,
  0.16492781043052673,
  0.12502165138721466,
  0.0936814695596695,
  0.080146923661232,
  0.06648611277341843,
  0.06414824724197388,
  0.05125407874584198],
 'val_accuracy': [0.8285909295082092,
  0.8996699452400208,
  0.9208968877792358,
  0.939847469329834,
  0.9484975934028625,
  0.9484975934028625,
  0.9535624980926514,
  0.9578306674957275,
  0.9619849920272827,
  0.9644320607185364],
 'val_loss': [0.5289369225502014,
  0.3082072138786316,
  0.24532604217529297,
  0.18350516259670258,
  0.15756267309188843,
  0.17162717878818512,
  0.1447140872478485,
  0.14734390377998352,
  0.1303354799747467,
  0.1222645491361618]}

Saving the model and history

In [24]:
model.save("model.h5")

In [ ]:
import json
with open("training_his.json","w") as f:
    json.dump(training_history.history,f)